### ISSUE TITLE
"Error: Invalid token entered"

### ISSUE THREAD

**Issue by rainabba** [mhdawson/google-auth-wrapper#3]
On day 2 and I'm SO close I can taste it, but I cannot get a token generated. Right now everything looks to be working as expected until I call provideCode() with the code (I've tried in the console and using debugger; see code below) but I keep getting back the error above. Any idea where to go from here?

One of the codes I'm getting back in case you want to confirm format: `4/AAD_GmuM4omj9EpmDUiRwPbylUlnyvfLx6J9wxJug7gl3_oFMHW17jk`

## My full code
```js
let path = require('path'),
    config = require("../private/config.js")(process.env, false, false),
    googleAuthCredentials = config.get('').authProviders.google.toString(),
    google_client_secret_folder = path.dirname(googleAuthCredentials),
    google_client_secret_file = path.basename(googleAuthCredentials).replace(/\.json$/g, "");
//Above is just to get the folder/file for credentials used in the call to .authorize()

var googleAuth = require('google-auth-wrapper');

googleAuth.authorize(google_client_secret_folder, google_client_secret_file, ['https://www.googleapis.com/auth/drive'],
    function(url, provideCode) {
        console.log('Please vist this url, authorize the app and return the code provided', url);
        let code = null;
        // Here I pull the URL from the console, get the code, then use the debugger to set code='{MyNewCode}' and resume. This happens in ~20 seconds so I'm sure it's not a timeout
        debugger;
        provideCode(code, function(err) {
            if (err !== undefined) {
              console.log('err:' + err);   // I'm seeing ```err:Error: Invalid token entered```
            } else {
              console.log('Success!');
            }
        });
    });
```

**Comment by mhdawson** [comment]
It should just be a cut and past of the code returned.  Have you tried the exact code on the readme ? 

```
var googleAuth = require('google-auth-wrapper');
var readline = require('readline');

googleAuth.authorize('./',
                     'client_secret',
                     ['https://www.googleapis.com/auth/drive'],
                     function(url, provideCode) {

  console.log('Please vist this url, authorize the app and return the code provided', url);
  var read = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  read.question('What was the code:?', function(code) {
    read.close();
    provideCode(code, function(err) {
      if (err !== undefined) console.log('err:' + err);
    });
  });
});
```

I know its unlikely there is something wrong with you have above, but testing with the code from the README.md would check with what worked for me before.

**Comment by rainabba** [comment]
In the end, I think it came down to the fact that your project was based on Google APIs 5.x and I had my dependencies set higher (would have been 25 or 29 at different points) and I never did try it standalone since I was sure you had and it would work there :)

This was my 3rd try and getting GoogleAPIs working for me in this project so I'm sure I was just being dense. This is what I ended up doing in the end. It's effectively your approach (which is basically their docs too), but I needed something that would also work well in Docker dev/ci/production and I love the Node Webkit debugger so I abused that for getting the code back in. https://github.com/rainabba/oauth-token-generator-google

Once I had that working, I took your drive wrapper and started a serious overhaul that is coming along nicely, built on API v29, is promisified (mostly anyway) and has a Lab/Code test suite to confirm AND demonstrate the uses (though I have quite a few more tests to write). If you'd like, I'll do a PR when I feel it's really ready. https://github.com/rainabba/google-drive-wrapper

**Comment by mhdawson** [comment]
PR sounds, good assuming it does not break existing users.  If it works with more up to date versions of the google APIs that would be great.

**Comment by rainabba** [comment]
SO much changed so fast and I decided to not only tackle this, but setup something that I can address other such APIs with. Today I finally got things far enough along that I've released: https://www.npmjs.com/package/node-cloudfs-drive

You have been given credit in the README and AUTHORS and the lineage was intact (my embarrassing code pre 1.0.0 included).

**Comment by mhdawson** [comment]
Thanks for the heads up and I'll try to take a look when I have time.
